export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_POST_DATA: "SET_POST_DATA",
  CLOSE_MODAL:"CLOSE_MODAL",
  ON_OPEN_MODAL: "ON_OPEN_MODAL",
  RESET_POST_DATA:'RESET_POST_DATA'
};
